### ISSUE TITLE
jira cloud update: JSONObject["name"] not found.

### ISSUE THREAD

**Issue by crsologicsde** [rastaman/jira-mylyn-connector#4]
some update from JIRA cloud. do you have an ideea?

thanks a lot.

`com.atlassian.connector.eclipse.internal.jira.core.service.JiraException: org.codehaus.jettison.json.JSONException: JSONObject["name"] not found.
`

```
com.atlassian.connector.eclipse.internal.jira.core.service.JiraException: com.atlassian.connector.eclipse.internal.jira.core.service.JiraException: org.codehaus.jettison.json.JSONException: JSONObject["name"] not found.
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:790)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssues(JiraRestClientAdapter.java:315)
	at com.atlassian.connector.eclipse.internal.jira.core.service.JiraClient.findIssues(JiraClient.java:368)
	at com.atlassian.connector.eclipse.internal.jira.core.service.JiraClient.search(JiraClient.java:757)
	at com.atlassian.connector.eclipse.internal.jira.core.JiraRepositoryConnector.performQuery(JiraRepositoryConnector.java:140)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:304)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:261)
	at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:192)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: com.atlassian.connector.eclipse.internal.jira.core.service.JiraException: org.codehaus.jettison.json.JSONException: JSONObject["name"] not found.
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:783)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.getIssue(JiraRestClientAdapter.java:248)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.access$3(JiraRestClientAdapter.java:247)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$5.call(JiraRestClientAdapter.java:325)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$5.call(JiraRestClientAdapter.java:1)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:746)
	... 8 more
Caused by: com.atlassian.jira.rest.client.RestClientException: org.codehaus.jettison.json.JSONException: JSONObject["name"] not found.
	at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient.invoke(AbstractJerseyRestClient.java:89)
	at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient.getAndParse(AbstractJerseyRestClient.java:106)
	at com.atlassian.jira.rest.client.internal.jersey.JerseyIssueRestClient.getIssue(JerseyIssueRestClient.java:133)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$3.call(JiraRestClientAdapter.java:250)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter$3.call(JiraRestClientAdapter.java:1)
	at com.atlassian.connector.eclipse.internal.jira.core.service.rest.JiraRestClientAdapter.call(JiraRestClientAdapter.java:746)
	... 13 more
Caused by: org.codehaus.jettison.json.JSONException: JSONObject["name"] not found.
	at org.codehaus.jettison.json.JSONObject.get(JSONObject.java:360)
	at org.codehaus.jettison.json.JSONObject.getString(JSONObject.java:487)
	at com.atlassian.jira.rest.client.internal.json.JsonParseUtil.parseBasicUser(JsonParseUtil.java:169)
	at com.atlassian.jira.rest.client.internal.json.CommentJsonParser.parse(CommentJsonParser.java:37)
	at com.atlassian.jira.rest.client.internal.json.CommentJsonParser.parse(CommentJsonParser.java:27)
	at com.atlassian.jira.rest.client.internal.json.JsonWeakParserForJsonObject.parse(JsonWeakParserForJsonObject.java:39)
	at com.atlassian.jira.rest.client.internal.json.IssueJsonParser.parseArray(IssueJsonParser.java:152)
	at com.atlassian.jira.rest.client.internal.json.IssueJsonParser.parse(IssueJsonParser.java:241)
	at com.atlassian.jira.rest.client.internal.json.IssueJsonParser.parse(IssueJsonParser.java:90)
	at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient$1.call(AbstractJerseyRestClient.java:111)
	at com.atlassian.jira.rest.client.internal.jersey.AbstractJerseyRestClient.invoke(AbstractJerseyRestClient.java:68)
	... 18 more

```

**Comment by rodrigc** [comment]
I started seeing this too, when using the Jenkins jira-plugin

**Comment by rodrigc** [comment]
Seems that other people are hitting this:
https://community.atlassian.com/t5/Jira-questions/JIRA-REST-API-missing-parameters/qaq-p/1302944

**Comment by rodrigc** [comment]
@crsologicsde You will need to update jira-mylyn-connector to use jira-rest-java-client 5.2.0 which was updated to fix this problem:  https://bitbucket.org/atlassian/jira-rest-java-client/pull-requests/93/jrjc-240-added-support-for-accountid/

**Comment by rastaman** [comment]
I will also update this project, apart if someone have a maintained fork better than mine, do you have ?

**Comment by rodrigc** [comment]
I don't have a fork of jira-mylyn-connector

**Comment by wayneb64** [comment]
I am having the same issue, I really hope we get an update for this since Atlassian are such crappy stewards of their product. Getting things to work in Eclipse seems terribly painful, at least to me.

**Comment by wayneb64** [comment]
Is there any status on getting this fixed? I realize this is all voluntary and thanks for any efforts. This is really important to me as it makes my work life so much better to have Jira integrated with Eclipse.

**Comment by p0las** [comment]
How can we get this fork to work? this was (as far as I know) the last working connector. Not having my tasks in eclipse really hurts my productivity. I don't know enough about Eclipse plugins to attempt to fix it myself.
